AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI with AWS SAM

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: yum-gdal-lambda-fronm-img
      Environment:
        Variables:
          ENDPOINT_URL: "s3.ap-southeast-2.wasabisys.com"
          AWS_ACCESS_KEY_ID: "2P801GRW1DVXZXRTE6NY"
          AWS_SECRET_ACCESS_KEY: "XuDYIb8rdl3fGH4SeKvBCyM7QDEzmebXukpqlNFK"
          GDAL_DATA: "/var/task/share/gdal"
          PROJ_LIB: "/var/task/share/proj"
          GDAL_CONFIG: "/var/task/bin/gdal-config"
          GEOS_CONFIG: "/var/task/bin/geos-config"
          GDAL_LIBRARY_PATH: "/var/task/lib/libgdal.so"
          GEOS_LIBRARY_PATH: "/var/task/lib/libgeos.so"
          CPLUS_INCLUDE_PATH: "/var/task/include/gdal"
          C_INCLUDE_PATH: "/var/task/include/gdal"
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Timeout: 30
